// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Simple greeting command for demonstration purposes.
 */
async greet(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("greet", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads user preferences from disk.
 * Returns default preferences if the file doesn't exist.
 */
async loadPreferences() : Promise<Result<AppPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves user preferences to disk.
 * Uses atomic write (temp file + rename) to prevent corruption.
 */
async savePreferences(preferences: AppPreferences) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends a native system notification.
 * On mobile platforms, returns an error as notifications are not yet supported.
 */
async sendNativeNotification(title: string, body: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_native_notification", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves emergency data to a JSON file for later recovery.
 * Validates filename and enforces a 10MB size limit.
 */
async saveEmergencyData(filename: string, data: JsonValue) : Promise<Result<null, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_emergency_data", { filename, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads emergency data from a previously saved JSON file.
 * Returns FileNotFound if the file doesn't exist.
 */
async loadEmergencyData(filename: string) : Promise<Result<JsonValue, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_emergency_data", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes recovery files older than 7 days.
 * Returns the count of removed files.
 */
async cleanupOldRecoveryFiles() : Promise<Result<number, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_old_recovery_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Shows the quick pane window and makes it the key window (for keyboard input).
 */
async showQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dismisses the quick pane window.
 * On macOS, resigns key window status before hiding to avoid activating main window.
 */
async dismissQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggles the quick pane window visibility.
 */
async toggleQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the default shortcut constant for frontend use.
 */
async getDefaultQuickPaneShortcut() : Promise<string> {
    return await TAURI_INVOKE("get_default_quick_pane_shortcut");
},
/**
 * Updates the global shortcut for the quick pane.
 * Pass None to reset to default.
 */
async updateQuickPaneShortcut(shortcut: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_quick_pane_shortcut", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check all dependencies and return their status
 */
async checkDependencies() : Promise<DependencyStatus> {
    return await TAURI_INVOKE("check_dependencies");
},
/**
 * Install Claude Code via npm
 * Emits 'install-progress' events with output lines
 */
async installClaudeCode() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_claude_code") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Spawn Claude Code in the specified directory
 */
async spawnClaude(cwd: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spawn_claude", { cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send input to the Claude Code session
 */
async sendInput(input: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_input", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resize the terminal
 */
async resizeTerminal(rows: number, cols: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resize_terminal", { rows, cols }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Kill the current PTY session
 */
async killSession() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kill_session") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if there's an active PTY session
 */
async hasActiveSession() : Promise<boolean> {
    return await TAURI_INVOKE("has_active_session");
},
/**
 * Check authentication status by looking for Claude config files
 */
async checkAuthStatus() : Promise<AuthStatus> {
    return await TAURI_INVOKE("check_auth_status");
},
/**
 * Get the Claude config directory contents (for debugging)
 */
async getClaudeConfigInfo() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_claude_config_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Application preferences that persist to disk.
 * Only contains settings that should be saved between sessions.
 */
export type AppPreferences = { theme: string; 
/**
 * Global shortcut for quick pane (e.g., "CommandOrControl+Shift+.")
 * If None, uses the default shortcut
 */
quick_pane_shortcut: string | null; 
/**
 * User's preferred language (e.g., "en", "es", "de")
 * If None, uses system locale detection
 */
language: string | null }
/**
 * Authentication status
 */
export type AuthStatus = { 
/**
 * Whether the user appears to be authenticated
 */
authenticated: boolean; 
/**
 * Path to the Claude config directory
 */
config_path: string | null }
/**
 * Status of required dependencies
 */
export type DependencyStatus = { 
/**
 * Node.js version if installed (e.g., "v20.10.0"), None if not found
 */
node: string | null; 
/**
 * Claude Code version if installed, None if not found
 */
claude: string | null; 
/**
 * Whether the user is authenticated with Anthropic
 */
authenticated: boolean }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Error types for recovery operations (typed for frontend matching)
 */
export type RecoveryError = 
/**
 * File does not exist (expected case, not a failure)
 */
{ type: "FileNotFound" } | 
/**
 * Filename validation failed
 */
{ type: "ValidationError"; message: string } | 
/**
 * Data exceeds size limit
 */
{ type: "DataTooLarge"; max_bytes: number } | 
/**
 * File system read/write error
 */
{ type: "IoError"; message: string } | 
/**
 * JSON serialization/deserialization error
 */
{ type: "ParseError"; message: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
